"""Grounding Validator — Phase 4 of the Resume Tailoring Pipeline.

Validates that all bullet points, skills, experiences, and metrics in the tailored
resume JSON produced by the Resume Tailoring Agent are strictly grounded in the
provided ResumeContext. Detects hallucinations, fabricated numbers, or ungrounded claims.
"""

import re
import logging
from typing import Dict, Any, List, Tuple

logger = logging.getLogger(__name__)


class GroundingValidator:
    """Validates tailored resume content against candidate graph evidence."""

    def validate(self, resume_json: Dict[str, Any], resume_context: Dict[str, Any]) -> Dict[str, Any]:
        """Validate structured resume JSON against the grounded ResumeContext.

        Args:
            resume_json: Tailored resume JSON generated by the agent.
            resume_context: The ResumeContext dict passed to the agent.

        Returns:
            Dict containing validation results:
                - is_valid (bool): True if grounding score >= threshold (e.g., 0.85)
                - grounding_score (float): 0.0 to 1.0 ratio of grounded claims
                - checked_claims (int): Total number of claims checked
                - ungrounded_claims (List[Dict]): List of specific flagged items
                - details (Dict): Section-by-section validation details
        """
        ungrounded = []
        total_claims = 0
        grounded_claims = 0

        # Build lookup set of candidate context tokens and entities for fast matching
        context_tokens, context_metrics, context_skills = self._build_context_lookups(resume_context)

        # 1. Validate Skills Section
        skills_res = self._validate_skills(resume_json.get("skills", []), context_skills)
        total_claims += skills_res["total"]
        grounded_claims += skills_res["grounded"]
        ungrounded.extend(skills_res["ungrounded"])

        # 2. Validate Work Experiences
        exp_res = self._validate_experiences(
            resume_json.get("experience", []),
            resume_context.get("experiences", []),
            context_tokens,
            context_metrics
        )
        total_claims += exp_res["total"]
        grounded_claims += exp_res["grounded"]
        ungrounded.extend(exp_res["ungrounded"])

        # 3. Validate Projects
        proj_res = self._validate_projects(
            resume_json.get("projects", []),
            resume_context.get("projects", []),
            context_tokens,
            context_metrics
        )
        total_claims += proj_res["total"]
        grounded_claims += proj_res["grounded"]
        ungrounded.extend(proj_res["ungrounded"])

        score = grounded_claims / total_claims if total_claims > 0 else 1.0

        is_valid = score >= 0.80 and len([u for u in ungrounded if u.get("severity") == "HIGH"]) == 0

        return {
            "is_valid": is_valid,
            "grounding_score": round(score, 3),
            "total_claims": total_claims,
            "grounded_claims": grounded_claims,
            "ungrounded_claims": ungrounded,
            "details": {
                "skills": skills_res,
                "experience": exp_res,
                "projects": proj_res,
            }
        }

    def _build_context_lookups(self, ctx: Dict[str, Any]) -> Tuple[set, set, set]:
        """Extract all valid tokens, metrics, and skill names from the candidate context."""
        context_tokens = set()
        context_metrics = set()
        context_skills = set()

        # Collect skills
        for cat in ctx.get("skills", {}).values():
            if isinstance(cat, list):
                for s in cat:
                    skill_name = s.get("name", s) if isinstance(s, dict) else str(s)
                    context_skills.add(skill_name.lower())
                    context_tokens.update(self._tokenize(skill_name))

        # Helper to index text and metrics
        def _index_text(text: str):
            if not text:
                return
            context_tokens.update(self._tokenize(text))
            # Extract numbers/metrics (e.g. 50%, 10x, 100k, 2.5)
            metrics = re.findall(r'\b\d+(?:\.\d+)?%?|\b\d+[kMBTx]?\b', text, re.IGNORECASE)
            for m in metrics:
                context_metrics.add(m.lower())

        # Index experiences
        for exp in ctx.get("experiences", []):
            _index_text(exp.get("company", ""))
            _index_text(exp.get("title", ""))
            _index_text(exp.get("description", ""))
            for bullet in exp.get("bullets", []):
                _index_text(bullet if isinstance(bullet, str) else bullet.get("text", ""))

        # Index projects
        for proj in ctx.get("projects", []):
            _index_text(proj.get("name", ""))
            _index_text(proj.get("description", ""))
            for bullet in proj.get("bullets", []):
                _index_text(bullet if isinstance(bullet, str) else bullet.get("text", ""))

        # Index achievements / evidence
        matched_ev = ctx.get("matched_evidence", {})
        if isinstance(matched_ev, dict):
            for skill_key, ev_data in matched_ev.items():
                if isinstance(ev_data, dict):
                    for item in ev_data.get("evidence", []):
                        if isinstance(item, dict):
                            _index_text(item.get("description", ""))
                            _index_text(item.get("project_name", ""))
                            _index_text(item.get("company", ""))
        elif isinstance(matched_ev, list):
            for ev in matched_ev:
                if isinstance(ev, dict):
                    _index_text(ev.get("evidence_text", ""))
                    _index_text(ev.get("description", ""))
                elif isinstance(ev, str):
                    _index_text(ev)


        return context_tokens, context_metrics, context_skills

    def _tokenize(self, text: str) -> List[str]:
        """Convert text into lowercase tokens for soft verification."""
        words = re.findall(r'\b[a-zA-Z0-9_-]+\b', text.lower())
        return [w for w in words if len(w) > 2]

    def _validate_skills(self, skills_list: List[Any], context_skills: set) -> Dict[str, Any]:
        """Check if skills in tailored resume exist in candidate context."""
        total = 0
        grounded = 0
        ungrounded = []

        # Handle list of category dicts or list of strings
        extracted_skills = []
        if isinstance(skills_list, list):
            for item in skills_list:
                if isinstance(item, dict):
                    for val in item.values():
                        if isinstance(val, list):
                            extracted_skills.extend(val)
                        elif isinstance(val, str):
                            extracted_skills.append(val)
                elif isinstance(item, str):
                    extracted_skills.append(item)

        for skill in extracted_skills:
            total += 1
            s_clean = str(skill).strip().lower()
            # Direct match or partial match in context_skills
            if s_clean in context_skills or any(s_clean in cs or cs in s_clean for cs in context_skills):
                grounded += 1
            else:
                ungrounded.append({
                    "section": "skills",
                    "claim": skill,
                    "reason": "Skill not present in candidate's original skill set",
                    "severity": "MEDIUM"
                })

        return {"total": total, "grounded": grounded, "ungrounded": ungrounded}

    def _validate_experiences(
        self,
        experiences: List[Dict[str, Any]],
        ctx_experiences: List[Dict[str, Any]],
        context_tokens: set,
        context_metrics: set
    ) -> Dict[str, Any]:
        """Validate experience entries and bullet points against context."""
        total = 0
        grounded = 0
        ungrounded = []

        valid_companies = {e.get("company", "").strip().lower() for e in ctx_experiences if e.get("company")}

        for exp in experiences:
            company = exp.get("company", "").strip()
            total += 1
            if company and (company.lower() in valid_companies or any(c in company.lower() for c in valid_companies)):
                grounded += 1
            else:
                ungrounded.append({
                    "section": "experience",
                    "claim": f"Company: {company}",
                    "reason": "Company name not found in candidate experience history",
                    "severity": "HIGH"
                })

            bullets = exp.get("bullets", [])
            for bullet in bullets:
                total += 1
                b_text = bullet if isinstance(bullet, str) else bullet.get("text", "")
                is_g, reason = self._check_bullet_grounding(b_text, context_tokens, context_metrics)
                if is_g:
                    grounded += 1
                else:
                    ungrounded.append({
                        "section": "experience",
                        "claim": b_text,
                        "reason": reason,
                        "severity": "HIGH" if "Fabricated metric" in reason else "MEDIUM"
                    })

        return {"total": total, "grounded": grounded, "ungrounded": ungrounded}

    def _validate_projects(
        self,
        projects: List[Dict[str, Any]],
        ctx_projects: List[Dict[str, Any]],
        context_tokens: set,
        context_metrics: set
    ) -> Dict[str, Any]:
        """Validate project entries and bullet points against context."""
        total = 0
        grounded = 0
        ungrounded = []

        valid_names = {p.get("name", "").strip().lower() for p in ctx_projects if p.get("name")}

        for proj in projects:
            pname = proj.get("name", "").strip()
            total += 1
            if pname and (pname.lower() in valid_names or any(n in pname.lower() for n in valid_names)):
                grounded += 1
            else:
                ungrounded.append({
                    "section": "projects",
                    "claim": f"Project: {pname}",
                    "reason": "Project name not found in candidate portfolio",
                    "severity": "HIGH"
                })

            bullets = proj.get("bullets", [])
            for bullet in bullets:
                total += 1
                b_text = bullet if isinstance(bullet, str) else bullet.get("text", "")
                is_g, reason = self._check_bullet_grounding(b_text, context_tokens, context_metrics)
                if is_g:
                    grounded += 1
                else:
                    ungrounded.append({
                        "section": "projects",
                        "claim": b_text,
                        "reason": reason,
                        "severity": "HIGH" if "Fabricated metric" in reason else "MEDIUM"
                    })

        return {"total": total, "grounded": grounded, "ungrounded": ungrounded}

    def _check_bullet_grounding(self, bullet: str, context_tokens: set, context_metrics: set) -> Tuple[bool, str]:
        """Check if a single bullet point's key terms and metrics exist in context."""
        if not bullet or len(bullet.strip()) < 5:
            return True, ""

        # 1. Check numbers/metrics in bullet
        bullet_metrics = re.findall(r'\b\d+(?:\.\d+)?%?|\b\d+[kMBTx]?\b', bullet, re.IGNORECASE)
        for m in bullet_metrics:
            m_clean = m.lower()
            if m_clean not in context_metrics:
                # Check if metric was in original string without exact formatting
                num_only = re.sub(r'[^\d]', '', m_clean)
                if num_only and not any(num_only in cm for cm in context_metrics):
                    return False, f"Fabricated metric '{m}' not grounded in candidate graph"

        # 2. Check token overlap (at least 30% of significant tokens must match context)
        b_tokens = self._tokenize(bullet)
        if not b_tokens:
            return True, ""

        matching_tokens = [t for t in b_tokens if t in context_tokens]
        overlap_ratio = len(matching_tokens) / len(b_tokens)

        if overlap_ratio < 0.25:
            return False, f"Low grounding overlap ({overlap_ratio:.0%}) with candidate evidence"

        return True, ""
